project:
  type: website
  output-dir: docs

website:
  title: "Quang Mai's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "CV"
        href: Quang_Mai_CV.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


